function start(){
    gapi.client.init({
        'apiKey': 'AIzaSyCc6gZwjBm2hDgyJGgUA_aFyM3KbfzGwGQ',
        'discoveryDocs': ['https://www.googleapis.com/discovery/v1/apis/books/v1/rest'],
    }).then(function(){
        /*Executes the API request and returns a promise generated by the API request.
          The method name gapi.client.books.volumes.list makes an API request to the Google Books API. It'll search for books based 
          on the query AKA "q" making sure the 'intitle' template string gets the value from the locally stored data 'mytext' and matches books to that title. 
        */
        return gapi.client.books.volumes.list({
            //q: `intitle:${localStorage.getItem('firstSearch')}`,
            q: `${localStorage.getItem('firstSearch')}`,

        });
    }).then(function(response){
        /*
        The response argument it's an object that represents the response from an API call
        In the case that the API call was successful:
        */
        let bookArray = response.result.items;
        let contentDiv = document.getElementById('content');

        if(bookArray){
            bookArray.forEach(function(book){
                if(book.volumeInfo && book.volumeInfo.imageLinks && book.volumeInfo.imageLinks.thumbnail){
                    let thumbnailLink = book.volumeInfo.imageLinks.thumbnail;

                    let thumbnailImage = document.createElement('img');
                    thumbnailImage.src = thumbnailLink;

                    contentDiv.appendChild(thumbnailImage);
                }
            });
        }
    },function(reason){
        /*
        In the case the API call was unsucessful:
        */
        alert('Error: '+ reason.result.error.message);
    });
};

gapi.load('client',start);

//localStorage.removeItem('mytext');